---
- name: Hello World!
  hosts: '{{ ansible_hosts }}'
 
  tasks:
 
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
